name: Update website
on:
  push:
    branches:
      - main
permissions: {}
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
      - name: Install node modules
        run: npm ci
      - uses: actions/configure-pages@v6
      - name: Build with MyST
        working-directory: docs
        env:
          # `BASE_URL` determines, relative to the root of the domain, the URL that your site is served from.
          # For example, if your site lives at `https://mydomain.org/myproject`, set `BASE_URL=/myproject`.
          # If, instead, your site lives at the root of the domain, at `https://mydomain.org`, set `BASE_URL=''`.
          BASE_URL: /${{ github.event.repository.name }}
        run: npx myst build --html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/_build/html
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      pages: write
      id-token: write
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
